name: Build C Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MinGW-w64
      run: sudo apt-get install -y mingw-w64

    - name: Compile C program
      run: x86_64-w64-mingw32-gcc -o my_program.exe my_program.c
