name: Compile C Program into EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run on the latest Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up MinGW
      run: |
        choco
