name: Compile C to EXE (Windows)

on:
  push:
    branches:
      - main  # Adjust this if you want to trigger for a different branch

jobs:
  build:
    runs-on: ubuntu-latest  # We're using Ubuntu as the base runner for now

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install MinGW (for cross-compiling C to EXE)
      - name: Install MinGW-w64
        run: sudo apt-get install -y mingw-w64

      # Step 3: Compile the .c file to .exe
      - name: Compile C file to EXE
        run: x86_64-w64-mingw32-gcc -o my_program.exe my_program.c  # Replace with your .c file name

      # Step 4: Upload the compiled EXE as an artifact (Updated to v4)
      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_program.exe  # Name of the file to upload
          path: my_program.exe  # Path to the compiled .exe file
