name: Compile C Program into EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows environment
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up MinGW
      uses: msys2/setup-msys2-action@v2
      with:
        msys2_packages: 'mingw-w64-x86_64-gcc'  # Installing MinGW with GCC for compilation

    - name: Compile C Program
      run: |
        mkdir build
        cd build
        x86_64-w64-mingw32-gcc ../tictactoe.c -o tictactoe.exe  # Compile the program

    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tictactoe-exe
        path: build/tictactoe.exe  # Path where the EXE is saved
