name: Build C Programs to EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MinGW
        run: |
          choco install mingw

      - name: Compile C program to app-debug.exe
        run: |
          x86_64-w64-mingw32-gcc -o app-debug.exe tictactoe.c
          dir   # List directory contents to ensure the .exe is created

      - name: Upload EXE file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-exe
          path: ./app-debug.exe  # Path where app-debug.exe is created
