name: Compile C Program into EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run on the latest Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up MinGW
      uses: msys2/setup-msys2-action@v4  # Set up MinGW using the MSYS2 action (v4)
      with:
        msys2-version: '20200724'  # Specify the MSYS2 version

    - name: Compile C code to EXE
      run: |
        x86_64-w64-mingw32-gcc -o app-debug.exe tictactoe.c  # Compile the program into app-debug.exe

    - name: Upload the compiled EXE as artifact
      uses: actions/upload-artifact@v2  # Upload the EXE as an artifact
      with:
        name: app-debug  # Artifact name in GitHub UI
        path: app-debug.exe  # Path to the compiled EXE file
